import * as React from "react"
import ReactDOM from "react-dom/client"
import "./styles.css"

type Status = "inbox"|"backlog"|"planned"|"done"|"archived"
type Item = { id:string, type:"idea"|"note"|"task", title:string, body:string, status:Status, priority:string, tags:string[], source:string, updated_at:string }
type Action = { op:"create"|"update"|"archive", id?:string, title?:string, body?:string, type?:string, status?:string, priority?:string, tags?:string[] }
const statuses:Status[] = ["inbox", "backlog", "planned", "done"]
const labels:Record<string,string> = { inbox:"Inbox", backlog:"Backlog", planned:"Planejado", done:"Concluído", archived:"Arquivado" }
const api = async (path:string, options:any = {}) => {
  const response = await fetch(path, { headers:{ "Content-Type":"application/json", ...(options.headers || {}) }, ...options })
  const data = await response.json()
  if(!response.ok || data?.ok === false) throw new Error(data?.message || data?.error || "A operação falhou")
  return data
}
const empty = ():Partial<Item> => ({ type:"idea", status:"inbox", priority:"none", title:"", body:"", tags:[] })
const tagsFrom = (value:string) => value.split(",").map((tag) => tag.trim()).filter(Boolean)

const ItemEditor = ({ item, onSave, onClose }:{ item:Partial<Item>, onSave:(data:Partial<Item>)=>Promise<void>, onClose:()=>void }) => {
  const [draft, setDraft] = React.useState<Partial<Item>>({ ...empty(), ...item }); const [saving, setSaving] = React.useState(false)
  const field = (key:keyof Item, value:any) => setDraft((current) => ({ ...current, [key]:value }))
  const save = async () => { if(!draft.title?.trim()) return; setSaving(true); try { await onSave({ ...draft, tags:tagsFrom((draft.tags || []).join(",")) }); onClose() } finally { setSaving(false) } }
  return <div className="modal" role="dialog"><div className="editor"><header><div><small>{item.id ? "DETALHES DO ITEM" : "NOVA CAPTURA"}</small><h2>{item.id ? "Editar item" : "Adicionar ao Blueprint"}</h2></div><button onClick={onClose}>×</button></header><label>Título<input autoFocus value={draft.title || ""} onChange={(e) => field("title", e.target.value)} placeholder="O que você quer registrar?"/></label><label>Conteúdo<textarea value={draft.body || ""} onChange={(e) => field("body", e.target.value)} placeholder="Contexto, observações ou próximo passo"/></label><div className="fields"><label>Tipo<select value={draft.type} onChange={(e) => field("type", e.target.value)}><option value="idea">Ideia</option><option value="note">Nota</option><option value="task">Tarefa</option></select></label><label>Status<select value={draft.status} onChange={(e) => field("status", e.target.value)}>{statuses.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></label><label>Prioridade<select value={draft.priority} onChange={(e) => field("priority", e.target.value)}>{["none","low","medium","high","critical"].map((priority) => <option key={priority} value={priority}>{priority}</option>)}</select></label></div><label>Tags<input value={(draft.tags || []).join(", ")} onChange={(e) => field("tags", tagsFrom(e.target.value))} placeholder="ex.: produto, reunião, urgente"/></label><footer><button onClick={onClose}>Cancelar</button><button className="primary" disabled={saving || !draft.title?.trim()} onClick={save}>{saving ? "Salvando…" : "Salvar item"}</button></footer></div></div>
}

const App = () => {
  const [items, setItems] = React.useState<Item[]>([]), [query, setQuery] = React.useState(""), [filter, setFilter] = React.useState(""), [editor, setEditor] = React.useState<Partial<Item>|null>(null), [notice, setNotice] = React.useState(""), [settings, setSettings] = React.useState(false), [apiKey, setApiKey] = React.useState(""), [model, setModel] = React.useState("gpt-4.1-mini"), [chat, setChat] = React.useState(""), [answer, setAnswer] = React.useState(""), [proposal, setProposal] = React.useState<Action[]>([]), [busy, setBusy] = React.useState(false)
  const load = async () => { try { const qs = new URLSearchParams(); if(query) qs.set("query", query); if(filter) qs.set("type", filter); setItems(await api(`/blueprint/items${qs.toString() ? `?${qs}` : ""}`)) } catch(e:any) { setNotice(e.message) } }
  React.useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer) }, [query, filter])
  const saveItem = async (data:Partial<Item>) => { try { if(data.id) { const { id, ...patch } = data; await api(`/blueprint/items/${id}`, { method:"PATCH", body:JSON.stringify(patch) }) } else await api("/blueprint/items", { method:"POST", body:JSON.stringify(data) }); await load(); setNotice("Item salvo no Blueprint.") } catch(e:any) { setNotice(e.message); throw e } }
  const move = async (item:Item, status:Status) => { await saveItem({ id:item.id, status }) }
  const archive = async (item:Item) => { if(!confirm(`Arquivar “${item.title}”?`)) return; try { await api(`/blueprint/items/${item.id}/archive`, { method:"POST", body:"{}" }); await load() } catch(e:any) { setNotice(e.message) } }
  const ask = async () => { if(!chat.trim()) return; setBusy(true); try { const result = await api("/blueprint/chat", { method:"POST", body:JSON.stringify({ message:chat, items }) }); setAnswer(result.message); setProposal(result.actions || []); setChat("") } catch(e:any) { setAnswer(e.message); setProposal([]) } finally { setBusy(false) } }
  const apply = async () => { if(!proposal.length) return; setBusy(true); try { const result = await api("/blueprint/actions/apply", { method:"POST", body:JSON.stringify({ actions:proposal }) }); setNotice(`${result.applied.length} ação(ões) aplicada(s).`); setProposal([]); await load() } catch(e:any) { setNotice(e.message) } finally { setBusy(false) } }
  const saveSettings = async () => { try { await api("/blueprint/settings", { method:"POST", body:JSON.stringify({ apiKey, model }) }); setApiKey(""); setSettings(false); setNotice("Configuração GPT salva somente no armazenamento local.") } catch(e:any) { setNotice(e.message) } }
  const visible = (status:Status) => items.filter((item) => item.status === status)
  return <main><header className="app-header"><div><small>PRODUCTIVITY WORKSPACE</small><h1>My Blueprint</h1><p>Capture agora. Estruture depois.</p></div><div className="header-actions"><button onClick={() => setSettings(true)}>Configurar GPT</button><button className="primary" onClick={() => setEditor(empty())}>+ Nova captura</button></div></header>
    {notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    <section className="quick-capture"><button className="capture-button" onClick={() => setEditor(empty())}><b>+</b><span><strong>Registrar uma ideia</strong><small>Abra uma captura rápida e organize depois.</small></span></button><div className="metrics"><span><b>{items.length}</b> ativos</span><span><b>{visible("inbox").length}</b> na inbox</span><span><b>{visible("done").length}</b> concluídos</span></div></section>
    <section className="toolbar"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por título, conteúdo ou tag"/><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">Todos os tipos</option><option value="idea">Ideias</option><option value="note">Notas</option><option value="task">Tarefas</option></select><button onClick={load}>Atualizar</button></section>
    <section className="board">{statuses.map((status) => <article key={status}><h2>{labels[status]} <small>{visible(status).length}</small></h2>{visible(status).length === 0 && <p className="empty">Nenhum item aqui.</p>}{visible(status).map((item) => <div className="card" key={item.id} onClick={() => setEditor(item)}><div className="card-meta"><span>{item.type}</span><span className={`priority-${item.priority}`}>{item.priority}</span></div><strong>{item.title}</strong>{item.body && item.body !== item.title && <p>{item.body}</p>}<div className="tags">{item.tags.map((tag) => <i key={tag}>#{tag}</i>)}</div><footer onClick={(event) => event.stopPropagation()}><select value={item.status} onChange={(e) => move(item, e.target.value as Status)}>{statuses.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select><button title="Arquivar" onClick={() => archive(item)}>⌫</button></footer></div>)}</article>)}</section>
    <section className="assistant"><div><small>ASSISTENTE GPT</small><h2>Transforme contexto em ação</h2><p>A IA propõe mudanças; você revisa e aplica somente o que quiser.</p><textarea value={chat} onChange={(e) => setChat(e.target.value)} placeholder="Ex.: agrupe essas ideias, crie as tarefas prioritárias e mova-as para o backlog"/><button className="primary" disabled={busy || !chat.trim()} onClick={ask}>{busy ? "Consultando…" : "Pedir sugestão"}</button></div><div className="assistant-result"><pre>{answer || "As sugestões aparecerão aqui."}</pre>{proposal.length > 0 && <><h3>{proposal.length} ação(ões) para revisão</h3><ol>{proposal.map((action, index) => <li key={index}><b>{action.op}</b> — {action.title || action.id}</li>)}</ol><button className="primary" disabled={busy} onClick={apply}>Aplicar ações aprovadas</button><button onClick={() => setProposal([])}>Descartar</button></>}</div></section>
    {editor && <ItemEditor item={editor} onSave={saveItem} onClose={() => setEditor(null)}/>} {settings && <div className="modal"><div className="editor"><header><div><small>CONFIGURAÇÃO LOCAL</small><h2>Conectar GPT</h2></div><button onClick={() => setSettings(false)}>×</button></header><p>A chave é armazenada somente no banco local deste aplicativo.</p><label>Chave OpenAI<input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="sk-…"/></label><label>Modelo<input value={model} onChange={(e) => setModel(e.target.value)}/></label><footer><button onClick={() => setSettings(false)}>Cancelar</button><button className="primary" disabled={!apiKey} onClick={saveSettings}>Salvar</button></footer></div></div>}
  </main>
}
ReactDOM.createRoot(document.getElementById("gui")!).render(<App />)
