const test = require("node:test") as typeof import("node:test")
const assert = require("node:assert/strict") as typeof import("node:assert/strict")
const fs = require("fs") as typeof import("fs")
const path = require("path") as typeof import("path")
const { InitializeBlueprintStore } = require("../src")
const file = path.join("/tmp", `my-blueprint-${process.pid}.sqlite`)
test("captura e organiza itens", async () => {
  fs.rmSync(file, { force: true })
  const store = await InitializeBlueprintStore({ storage: file })
  const item = await store.CreateItem({ title: "Ideia de produto", tags: ["produto"] })
  assert.equal(item.status, "inbox")
  const updated = await store.UpdateItem(item.id, { type: "task", status: "backlog", priority: "high" })
  assert.equal(updated.type, "task")
  assert.equal((await store.ListItems({ status: "backlog" })).length, 1)
  await store.Close()
})
